---

- name: Create our apache config files
  template:
    src: "{{ role_path }}/templates/apache-nextcloud.conf"
    dest: "{{ nc_conf_destination }}"
    owner: "root"
    mode: "0644"
    group: "root"
