---

- name: Create our base install script
  template:
    src: "{{ role_path }}/templates/base-install.sh.j2"
    dest: "{{ base_install_script }}"
    mode: u+x

- name: Perform base install
  shell: "{{ base_install_script }} > /var/log/base-install.log"
  args:
    creates: /var/log/base-install.log
