---

- name: Cleanup our files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ import_config_file }}"
    - "{{ samba_pass_sh_script }}"
    - "{{ input_file }}"
    - "{{ shares_script }}"
#    - "{{ base_install_script }}"
