---

- name: Create our Nextcloud config file for import
  template:
    src: "{{ role_path }}/templates/nextcloud-conf.json.j2"
    dest: "/usr/share/httpd/nextcloud-conf.json"
    owner: "apache"
    mode: "0644"
    group: "apache"

- name: Create our Nextcloud importer script
  template:
    src: "{{ role_path }}/templates/import-config.sh.j2"
    dest: "/root/import-config.sh"
    mode: u+x

- name: Import our Nextcloud config
  shell: /root/import-config.sh > /var/log/nextcloud-import.log
  args:
    creates: /var/log/nextcloud-import.log
