---

- name: Create our Nextcloud config file for import
  template:
    src: "{{ role_path }}/templates/nextcloud-conf.json.j2"
    dest: "/usr/share/httpd/nextcloud-conf.json"
    owner: "{{ web_user }}"
    mode: "0644"
    group: "{{ web_group }}"

- name: Create our Nextcloud importer script
  template:
    src: "{{ role_path }}/templates/import-config.sh.j2"
    dest: "{{ config_sh_script}}"
    mode: u+x

- name: Import our Nextcloud config
  shell: "{{ config_sh_script}} > /var/log/nextcloud-import.log"
  args:
    creates: /var/log/nextcloud-import.log
