---

- name: Configure apache
  include: apache.yml

- name: Add our nextcloud config
  include: create-config.yml

- name: Add our shared folders
  include: shared-folders.yml

- name: Add our Samba services
  include: samba.yml

- name: Restart httpd and smb services
  include: restart-services.yml

- name: Create our NC Backups
  include: backup.yml

- name: Clean up our files
  include: cleanup.yml
