---

- name: Configure apache
  include: apache.yml

- name: Add our nextcloud config
  include: create-config.yml

- name: Add our shared folders
  include: shared-folders.yml

- name: Add our Samba services
  include: samba.yml
