---

- name: Create our file retention script
  template:
    src: "{{ role_path }}/templates/retention.sh.j2"
    dest: "/root/retention.sh"
    mode: u+x

- name: Create our file retention cron job"
  cron:
    name: "Clear files and folders older than 30 days"
    minute: "00"
    hour: "18"
    job: "/usr/bin/flock -n {{ data_dir }}lock/retention.sh.lock /root/retention.sh"

- name: Create TEMP FILES TEST
  template:
    src: "{{ role_path }}/templates/create_old_files.sh.j2"
    dest: "/root/temp_create_old_files.sh"
    mode: u+x
