---

- name: Create our samba group
  group:
    name: "{{ samba_group }}"
    state: present
    gid: "{{ samba_group_gid }}"

- name: Create our samba user
  user:
    name: {{ report_user }}
    groups: {{ samba_group }},{{ web_group }}
    append: yes
    uid: {{ report_user_uid }}
