---

- name: Create our samba group
  group:
    name: "{{ samba_group }}"
    state: present
    gid: "{{ samba_group_gid }}"

- name: Create our samba user
  user:
    name: "{{ report_user }}"
    groups: "{{ samba_group }}, {{ web_group }}"
    append: yes

- name: Add samba group to our web user
  user:
    name: "{{ web_user }}"
    groups: "{{ samba_group }}"
    append: yes
