---

- name: create our CRC shared folders
  file:
    path: "{{ data_dir}}{{ nextcloud_admin }}/{{ share_files_root }}/CRC/{{ item }}"
    state: directory
    group: "{{ web_group }}"
    mode: "0770"
    owner: "{{ web_user }}"
    recurse: yes
  with_items:
    - 'bench'
    - 'bgsw'
    - 'cgm'
    - 'cl'
    - 'ddc'
    - 'dlnr'
    - 'dtv'
    - 'essex'
    - 'hampshire'
    - 'hlny'
    - 'kss'
    - 'london'
    - 'merseyside'
    - 'misc'
    - 'northumbria'
    - 'ns'
    - 'south-yorkshire'
    - 'swm'
    - 'thames'
    - 'wales'
    - 'west-yorkshire'
    - 'wwm'


- name: create our NPS shared folders
  file:
    path: "{{ data_dir}}{{ nextcloud_admin }}/{{ share_files_root }}/NPS/{{ item }}"
    state: directory
    group: "{{ web_group }}"
    mode: "0770"
    owner: "{{ web_user }}"
    recurse: yes
  with_items:
    - 'NorthWest'
    - 'NorthEast'
    - 'Wales'
    - 'SouthWestandSouthCentral'
    - 'SouthEastandEastern'
    - 'London'
    - 'EPP'
    - 'PPAS'
    - 'GreaterManchester'
    - 'WestMidlands'
    - 'EastMidlands'

- name: create our National shared folders
  file:
    path: "{{ data_dir}}{{ nextcloud_admin }}/{{ share_files_root }}/National/{{ item }}"
    state: directory
    group: "{{ web_group }}"
    mode: "0770"
    owner: "{{ web_user }}"
    recurse: yes
  with_items:
    - 'cfo'
    - 'wmt'

- name: create our other top level shared folders
  file:
    path: "{{ data_dir}}{{ nextcloud_admin }}/{{ share_files_root }}/{{ item }}"
    state: directory
    group: "{{ web_group }}"
    mode: "0770"
    owner: "{{ web_user }}"
    recurse: yes
  with_items:
    - 'nart'
