---

- name: Create our upgrade install script
  template:
    src: "{{ role_path }}/templates/nextcloud-upgrade.sh.j2"
    dest: "/root/nextcloud-upgrade.sh"
    mode: u+x

##Temp for test
- name: Create our Nextcloud config file for import
  template:
    src: "{{ role_path }}/templates/V20nextcloud-conf.json.j2"
    dest: "/usr/share/httpd/V20nextcloud-conf.json"
    owner: "{{ web_user }}"
    mode: "0644"
    group: "{{ web_group }}"
