---

- name: Set accoumt name ssm fact
  set_fact:
    wmt_account: "{{ lookup('aws_ssm', '{{nextcloud_ssm_path }}/wmt-account', decrypt=True, region='eu-west-2') }}"
  when: env_type == "prod"

- name: Set account key ssm fact
  set_fact:
    wmt_account_key: "{{ lookup('aws_ssm', '{{nextcloud_ssm_path }}/wmt-account-key', decrypt=True, region='eu-west-2') }}"
  when: env_type == "prod"

- name: Create our upload_wmt.py script
  template:
    src: "{{ role_path }}/templates/upload-wmt.py.j2"
    dest: "/usr/local/sbin/upload_wmt.py"
    owner: "root"
    mode: "0644"
    group: "root"
  when: env_type == "prod"

- name: Create our upload cron job"
  cron:
    name: "Upload WMT Files to Kainos"
    minute: "20"
    hour: "05"
    job: "/usr/bin/flock -n {{ data_dir }}lock/upload_wmt.py.lock /usr/local/sbin/upload_wmt.py"
  when: env_type == "prod"
