---

- name: Set accoumt name ssm fact
  set_fact:
    wmt_account: "{{ lookup('aws_ssm', '{{nextcloud_ssm_path }}/wmt-account', decrypt=True, region='eu-west-2') }}"
  when: env_type == "prod"

- name: Set account key ssm fact
  set_fact:
    wmt_account_key: "{{ lookup('aws_ssm', '{{nextcloud_ssm_path }}/wmt-account-key', decrypt=True, region='eu-west-2') }}"
  when: env_type == "prod"

- name: Create our upload_wmt.py script
  template:
    src: "{{ role_path }}/templates/upload-wmt.py.j2"
    dest: "/usr/local/sbin/upload_wmt.py"
    owner: "root"
    mode: "u+x"
    group: "root"
  when: env_type == "prod"

- name: Create our upload cron job
  cron:
    name: "Upload WMT Files to Kainos"
    minute: "20"
    hour: "05"
    job: "/usr/bin/flock -n {{ data_dir }}lock/upload_wmt.py.lock /usr/local/sbin/upload_wmt.py"
  when: env_type == "prod"

- name: Install Azure Storage file
  pip:
    name: azure-storage-file
  when: env_type == "prod"

- name: Add sftp server to hosts files
  lineinfile:
    path: /etc/hosts
    line: "51.141.15.114 wmt-prd-sftp"
  when: env_type == "prod"

#------------------------------------------------------------------------------
# Script to replace existing upload-wmt.py
# Files will no longer be  sent to Kainos Azure File Server
# Files will be sent to S3 Bucket in cloud platform
#------------------------------------------------------------------------------
- name: Create WMT log directory
  file:
    path: "/var/log/wmt"
    state: directory
    group: "root"
    mode: "0700"
    owner: "root"
  when: env_type == "mis-dev"

- name: Create our WMT upload log
  file:
    path: "/var/log/wmt/wmt.log"
    state: touch
    owner: "root"
    mode: "0644"
    group: "root"
  when: env_type == "mis-dev"

- name: Create our Cloud Platform s3_upload_wmt.sh script
  template:
    src: "{{ role_path }}/templates/s3_upload_wmt.sh.j2"
    dest: "/usr/local/sbin/s3_upload_wmt.sh"
    owner: "root"
    mode: "u+x"
    group: "root"
  when: env_type == "mis-dev"

- name: Cron to upload WMT Extracts to S3
  cron:
    name: "Upload WMT Extracts to CloudPlatform"
    minute: "20"
    hour: "05"
    job: "/usr/bin/flock -n {{ data_dir }}lock/s3_upload_wmt.sh.lock /usr/local/sbin/s3_upload_wmt.sh"
  when: env_type == "mis-dev"
